name := "rest-akka-http"
version := "1.0"
scalaVersion := "2.13.1"
libraryDependencies += "com.typesafe.akka" %% "akka-http"   % "10.1.10" 
libraryDependencies += "com.typesafe.akka" %% "akka-stream" % "2.5.26" 